composition:
  title: "il mondo dorme"

streams:
  - stream_id: "texture1"
    onset: 0.0
    duration: 2.0
    sample: "008-1_778-_560.wav"
    grain:
      duration: .1      
      envelope: half_sine
    density: 3         
    distribution: 0
    pointer:
      start: 0.0        
      mode: linear      
      speed: .03   
    pitch:
      shift_semitones: 0
    output:
      pan: 0.5          
      volume: -6        
    # -----------------------------------------------------------------
  - stream_id: "texture1"
    onset: 2
    duration: 2.0
    sample: "008-1_778-_560.wav"
    grain:
      duration: .1      
      envelope: half_sine
    density: 5         
    distribution: 0
    pointer:
      start: 0.0        
      mode: linear      
      speed: .03   
    pitch:
      shift_semitones: 0
    output:
      pan: 0.5          
      volume: -6        
    # -----------------------------------------------------------------
  - stream_id: "texture1"
    onset: 4.0
    duration: 2.0
    sample: "008-1_778-_560.wav"
    grain:
      duration: .1      
      envelope: half_sine
    density: 7         
    distribution: 0
    pointer:
      start: 0.0        
      mode: linear      
      speed: .03   
    pitch:
      shift_semitones: 0
    output:
      pan: 0.5          
      volume: -6        
    # -----------------------------------------------------------------
  - stream_id: "texture1"
    onset: 6.0
    duration: 2.0
    sample: "008-1_778-_560.wav"
    grain:
      duration: .1      
      envelope: half_sine
    density: 10         
    distribution: 0
    pointer:
      start: 0.0        
      mode: linear      
      speed: .03   
    pitch:
      shift_semitones: 0
    output:
      pan: 0.5          
      volume: -6        
    # -----------------------------------------------------------------
  - stream_id: "texture1"
    onset: 8.0
    duration: 2.0
    sample: "008-1_778-_560.wav"
    grain:
      duration: .1      
      envelope: half_sine
    density: 15        
    distribution: 0
    pointer:
      start: 0.0        
      mode: linear      
      speed: .03   
    pitch:
      shift_semitones: 0
    output:
      pan: 0.5          
      volume: -6        
    # -----------------------------------------------------------------
  - stream_id: "texture1"
    onset: 10.0
    duration: 2.0
    sample: "008-1_778-_560.wav"
    grain:
      duration: .1      
      envelope: half_sine
    density: 20         
    distribution: 0
    pointer:
      start: 0.0        
      mode: linear      
      speed: .03   
    pitch:
      shift_semitones: 0
    output:
      pan: 0.5          
      volume: -6        
    # -----------------------------------------------------------------
  - stream_id: "texture1"
    onset: 12.0
    duration: 2.0
    sample: "008-1_778-_560.wav"
    grain:
      duration: .1      
      envelope: half_sine
    density: 30         
    distribution: 0
    pointer:
      start: 0.0        
      mode: linear      
      speed: .03   
    pitch:
      shift_semitones: 0
    output:
      pan: 0.5          
      volume: -6        
    # -----------------------------------------------------------------
  - stream_id: "texture1"
    onset: 14.0
    duration: 2.0
    sample: "008-1_778-_560.wav"
    grain:
      duration: .1      
      envelope: half_sine
    density: 40         
    distribution: 0
    pointer:
      start: 0.0        
      mode: linear      
      speed: .03   
    pitch:
      shift_semitones: 0
    output:
      pan: 0.5          
      volume: -6        
    # -----------------------------------------------------------------
  - stream_id: "texture1"
    onset: 16.0
    duration: 2.0
    sample: "008-1_778-_560.wav"
    grain:
      duration: .1      
      envelope: half_sine
    density: 50         
    distribution: 0
    pointer:
      start: 0.0        
      mode: linear      
      speed: .03   
    pitch:
      shift_semitones: 0
    output:
      pan: 0.5          
      volume: -12
    # -----------------------------------------------------------------
  - stream_id: "texture1"
    onset: 18.0
    duration: 2.0
    sample: "008-1_778-_560.wav"
    grain:
      duration: .1      
      envelope: half_sine
    density: 75         
    distribution: 0
    pointer:
      start: 0.0        
      mode: linear      
      speed: .03   
    pitch:
      shift_semitones: 0
    output:
      pan: 0.5          
      volume: -12
    # -----------------------------------------------------------------
  - stream_id: "texture1"
    onset: 20.0
    duration: 2.0
    sample: "008-1_778-_560.wav"
    grain:
      duration: .1      
      envelope: half_sine
    density: 100         
    distribution: 0
    pointer:
      start: 0.0        
      mode: linear      
      speed: .03   
    pitch:
      shift_semitones: 0
    output:
      pan: 0.5          
      volume: -18
    # -----------------------------------------------------------------
  - stream_id: "texture1"
    onset: 22.0
    duration: 2.0
    sample: "008-1_778-_560.wav"
    grain:
      duration: .1      
      envelope: half_sine
    density: 250         
    distribution: 0
    pointer:
      start: 0.0        
      mode: linear      
      speed: .03   
    pitch:
      shift_semitones: 0
    output:
      pan: 0.5          
      volume: -24
    # -----------------------------------------------------------------
  - stream_id: "texture1"
    onset: 24.0
    duration: 2.0
    sample: "008-1_778-_560.wav"
    grain:
      duration: .1      
      envelope: half_sine
    density: 500         
    distribution: 0
    pointer:
      start: 0.0        
      mode: linear      
      speed: .03   
    pitch:
      shift_semitones: 0
    output:
      pan: 0.5          
      volume: -24
    # -----------------------------------------------------------------
  - stream_id: "texture1"
    onset: 26.0
    duration: 2.0
    sample: "008-1_778-_560.wav"
    grain:
      duration: .1      
      envelope: half_sine
    density: 1000         
    distribution: 0
    pointer:
      start: 0.0        
      mode: linear      
      speed: .03   
    pitch:
      shift_semitones: 0
    output:
      pan: 0.5          
      volume: -24        
    # -----------------------------------------------------------------
