composition:
  title: "il mondo dorme"

streams:
  - stream_id: "texture1"
    onset: 0.0
    duration: 5.0
    sample: "016.wav"
    grain:
      duration: .03      
      envelope: half_sine
    pointer:
      start: 0.5       
      mode: linear     
      speed: .5
      jitter: 0.001
    output:
      pan: 0.5          
      volume: -6        
    # -----------------------------------------------------------------
  - stream_id: "texture1"
    onset: 5.0
    duration: 5.0
    sample: "016.wav"
    grain:
      duration: [[0,.03],[4,.33]]      
      envelope: half_sine
    density: 3         
    distribution: 0
    pointer:
      start: 0.5      
      mode: linear      
      speed: .5  
      jitter: 0.001
    pitch:
      shift_semitones: 0
    output:
      pan: 0.5          
      volume: -6        
    # -----------------------------------------------------------------
  - stream_id: "texture1"
    onset: 10.0
    duration: 5.0
    sample: "016.wav"
    grain:
      duration: 
        type: cubic
        points: [[0,.03],[4,.33]]      
      envelope: half_sine
    density: 3         
    distribution: 0
    pointer:
      start: .5       
      mode: linear      
      speed: .5
      jitter: 0.001
    pitch:
      shift_semitones: 0
    output:
      pan: 0.5          
      volume: -6        
    # -----------------------------------------------------------------
  - stream_id: "texture1"
    onset: 15.0
    duration: 5.0
    sample: "016.wav"
    grain:
      duration: .03      
      envelope: half_sine
    density: 3         
    distribution: 0
    pointer:
      start: 4.0       
      mode: linear      
      speed: .25 
      jitter: 0.001
    pitch:
      shift_semitones: 0
    output:
      pan: 0.5          
      volume: -6        
    # -----------------------------------------------------------------