composition:
  title: "il mondo dorme"

streams:
  - stream_id: "texture1"
    onset: 0.0
    duration: 1580
    sample: "016.wav"
    grain:
      duration: .01      
      overlap_factor: 2
      #reverse: false
    density: 10        
    distribution: 0
    pointer:
      jitter: 0.001
      start: 0.0        
      mode: linear
      speed: 0
    pitch:
      shift_semitones: 0
    output:
      pan: 0.5          
      volume: -6        
    # -----------------------------------------------------------------
