composition:
  title: "il mondo dorme"

streams:
  - stream_id: "texture1"
    onset: 0.0
    duration: 10
    time_mode: normalized
    sample: "016-39_8-2_2.wav"
    grain:
      duration: 0.05
      envelope: triangle
    pointer:     
      speed: 
        type: cubic
        points: [[0,1],[.25,2],[.5,4],[.7,8],[1,-1]]
      loop_unit: normalized
      loop_start: 0
      loop_end: 0.454545
    # -----------------------------------------------------------------