composition:
  title: "il mondo dorme"

streams:
  - stream_id: "texture1"
    onset: 0.0
    duration: 25.0
    time_mode: normalized
    sample: "016-39_8-2_2.wav"
    grain:
      duration: 0.05
      envelope: triangle
    pointer:     
      speed: 
        type: step
        points: [[0,1],[0.5,2],[1.0,-1]]
      loop_start: 0.1
      loop_end: 0.7
    # -----------------------------------------------------------------