composition:
  title: "il mondo dorme"

streams:
  - stream_id: "texture1"
    time_mode: normalized
    onset: 0.0
    duration: 30
    density: 1
    sample: "sinus.wav"
    grain:
      duration: .4