composition:
  title: "il mondo dorme"

streams:
  - stream_id: "texture1"
    time_mode: normalized
    onset: 0.0
    duration: 30
    fill_factor: 1
    sample: "pino2.wav"
    grain:
      duration: .1
      reverse: