composition:
  title: "il mondo dorme"

streams:
  - stream_id: "texture1"
    time_mode: normalized
    onset: 0.0
    duration: 30
    sample: "pino2.wav"
    range_always_active: 
    grain:
      duration: 0.1
    dephase: 0