composition:
  title: "il mondo dorme"

streams:
  - stream_id: "texture1"
    time_mode: normalized
    onset: 0.0
    duration: 10
    sample: "sinus.wav"
    #range_always_active: 
    density: 5
    grain:
      duration: 0.1
      duration_range: .2
    dephase: 
      volume: 0
      pitch: 0
      pan: 0
      duration: 
        type: 'step'
        points: [[0,0],[.5,100],[.75,20]]
      reverse: 0
      pointer: 0