composition:
  title: "il mondo dorme"

streams:
  - stream_id: "texture1"
    time_mode: normalized
    onset: 0.0
    duration: 30
    sample: "pino2.wav"
    #range_always_active: 
    distribution_mode: 'gaussian'
    density: 
      type: cubic
      points: [[0,10],[.4,200],[1, 50]]
    distribution: .5
    pointer:
      speed: 1
      loop_start: 0
      loop_dur: [[0,0.1],[.1,0.02], cycle]
    grain:
      duration: .05
      #duration_range: .05
      #envelope: ['gaussian', 'hanning', 'expodec']
      #envelope_range: 1.0
    dephase:
      type: cubic
      points: [[0,2],[.4,40],[1,10]]
