composition:
  title: "il mondo dorme"

streams:
  - stream_id: "texture1"
    time_mode: normalized
    onset: 0.0
    duration: 30
    #time_scale: .3
    sample: "pino2.wav"
    #range_always_active: 
    distribution_mode: 'gaussian'
    #fill_factor: [[0,.3],[.1,4], cycle]
    density: 
      type: cubic
      points: [[0,10],[.3,10],[[[0,5],[10,50], [100,30]], 1.0, 5]]
    distribution: [[0,0],[.5,1],[1,0]]
    pointer:
      speed_ratio: [[[0,-1],[100,1]],1.0,10]
      #loop_start: [[0,0.3],[.1,0.3],[0.2,0.3],[.3,0.4], cycle]
      #loop_dur: [[0,0.2],[.1,0.02], cycle]
    grain:
      duration: [[0,.05],[.5,0.08],[[[0,.3],[10,.02], [100,.08]], 1.0, 5]]
      duration_range: .01
      #envelope: ['gaussian', 'hanning', 'expodec']
      #envelope_range: 1.0
    dephase:
      type: 'cubic'
      points: [[0,50],[.5,0],[1,30]]