composition:
  title: "il mondo dorme"

streams:
  - stream_id: "texture1"
    time_mode: normalized
    onset: 0.0
    duration: (60)
    range_always_active:
    sample: "001-0_0-3_0.wav"
    pointer:
      #loop_unite: absolute
      loop_start: [[[0,.2],[100,1.0]],1.0,5]
      loop_dur: [[[0,.2],[100,1.0]],1.0,5]
      speed_ratio: .003
      #speed_ratio: [[[0,-1],[25,0.1],[75,.4],[100,1]],1.0,3]
    density: 2000
    distribution: 1
    grain:
      duration: .05
      duration_range: .02
      reverse:
    volume: -20
    dephase: [[0,1],[.5,100],[1,0]]