composition:
  title: "il mondo dorme"

streams:
  - stream_id: "texture1"
    time_mode: normalized
    onset: 0.0
    duration: 10
    sample: "pino2.wav"
    #range_always_active: 
    distribution_mode: 'gaussian'
    density: 20
    pointer:
      speed: .5
    grain:
      duration: 2
      duration_range: .05
      envelope: ['gaussian', 'hanning', 'expodec']
      envelope_range: 1.0
    pan: 70
    pan_range: 140
