composition:
  title: "il mondo dorme"

streams:
  - stream_id: "texture1"
    time_mode: normalized
    onset: 0.0
    duration: 10
    sample: "pino2.wav"
    #range_always_active: 
    distribution_mode: 'gaussian'
    density: 20
    grain:
      duration: 0.1
      duration_range: .05
      envelope: all
      envelope_range: 1.0
