composition:
  title: "il mondo dorme"

streams:
  - stream_id: "texture1"
    time_mode: "normalized"
    onset: 0.0
    duration: 60
    #range_always_active:
    sample: "001-0_0-3_0.wav"
    pointer:
      #loop_unite: absolute
      #loop_start: [[[0,.6],[100,.1]],1,5]
      #loop_dur: [[[0,.6],[100,.1]],1,3]
      speed_ratio: .003
      offset_range: .2
      #speed_ratio: [[[0,-1],[25,0.1],[75,.4],[100,1]],1.0,3]
    density: 2000
    distribution: 1
    grain:
      duration: .05
      duration_range: .02
      reverse:
    volume: -30
    dephase: [[0,1],[.5,100],[1,0]]
    pan: [[0,40],[.6,-30],[1,-70]]

  - stream_id: "texture1"
    time_mode: "normalized"
    onset: 7
    duration: 70
    #range_always_active:
    sample: "002-34_468-3_219.wav"
    pointer:
      #loop_unite: absolute
      loop_start: [[[0,.6],[100,.3]],1,5]
      loop_dur: [[[0,.6],[100,.3]],1,5]
      speed_ratio: .03
      offset_range: .2
      #speed_ratio: [[[0,-1],[25,0.1],[75,.4],[100,1]],1.0,3]
    density: 3000
    distribution: 1
    grain:
      duration: .05
      duration_range: .02
      reverse:
    volume: -20
    dephase: [[0,1],[.5,100],[1,0]]
    pan_range: [[0,60],[1,100]]

