composition:
  title: "il mondo dorme"

streams:
  - stream_id: "texture1"
    onset: 0.0
    duration: 39.7
    sample: "pino2.wav"
    grain:
      duration: 0.05
    fill_factor: 2
    pointer:     
      speed: 0.5  #speed_ratio
      #jitter:
        #type: step 
        #points: [[0,0],[4,0.005],[8,0.01],[12,0.02],[16,0.04],[20,0.08]]
    envelope: gaussian
    dephase:
      pc_rand_reverse: 0 
      pc_rand_pan: 0
      pc_rand_volume: 0
      pc_rand_duration: 
        time_unit: 'normalized'
        type: 'step'
        points: [[0,0.000],[.100,2.863],[.200,6.644],[.300,11.634],[.400,18.223],[.500,26.921],[.600,38.404],[.700,53.564],[.800,73.578],[.900,100.000]]
    # -----------------------------------------------------------------

  - stream_id: "texture1"
    onset: 0.0
    duration: 39.7
    solo:
    sample: "pino2.wav"
    grain:
      duration: 0.05
    fill_factor: 2
    pointer:     
      speed: 0.5  #speed_ratio
      #jitter:
        #type: step 
        #points: [[0,0],[4,0.005],[8,0.01],[12,0.02],[16,0.04],[20,0.08]]
    envelope: gaussian
    dephase:
      pc_rand_reverse: 
        time_unit: 'normalized'
        type: 'step'
        points: [[0,0.000],[.100,2.863],[.200,6.644],[.300,11.634],[.400,18.223],[.500,26.921],[.600,38.404],[.700,53.564],[.800,73.578],[.900,100.000]]
    # -----------------------------------------------------------------


# elementi di micromodulazione che scompaginano la periodicità:
# sfasamento statistico della fase attraverso
# la lettura in reverse con una maschera di scelta su
# percentuale... per esempio numero randomico e percentuale di scelta tipo > 50 o > 90 etc

# sfasametneo del pan.

# sfasamento statistico della ampiezza del singolo grano anche questo secondo maschera. leggermente modulata.

# sfasamento statistico sulla durata dei grani.


# elementi di sfasamento di voce
# utilizzo di velocità di lettura in modalità harmonising per avere voci che coprono zone diverse di altezze.


# song of songs TRUAX
# ash Vaggione